# Generated by Django 4.1.3 on 2022-11-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_alter_dish_cooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveIntegerField(),
        ),
    ]
